# See: https://github.com/drone/drone/blob/v0.4.0/docs/build/README.md
build:

  build:
    image: jprobinson/ae-go-buildbox:1.6
    pull: true
    environment:
      - GOPATH=/drone
      - PATH=/usr/bin:/usr/local/go_appengine
    commands:
      - goapp get -v ./...
    when:
      event: [push, pull_request, tag]

deploy:

  ##################
  # LAB ENVIRONMENT
  ##################
  gae:
    environment:
      - GOPATH=/drone
    image: nytimes/drone-gae
    action: update
    project: games-puzzles-sandbox
    version: "$$COMMIT"
    token: >
      $$GOOGLE_CREDENTIALS_LAB
    when:
      event: push
      branch: master

  gae:
    image: nytimes/drone-gae
    action: set_default_version
    project: games-puzzles-sandbox
    version: "$$COMMIT"
    token: >
      $$GOOGLE_CREDENTIALS_LAB
    when:
      event: push
      branch: master

  ##################
  # DEV ENVIRONMENT
  ##################
  gae:
    environment:
      - GOPATH=/drone
    image: nytimes/drone-gae
    action: update
    project: nyt-games-dev
    version: "$$COMMIT"
    token: >
      $$GOOGLE_CREDENTIALS_DEV
    when:
      event: push
      branch: master

  gae:
    image: nytimes/drone-gae
    action: set_default_version
    project: nyt-games-dev
    version: "$$COMMIT"
    token: >
      $$GOOGLE_CREDENTIALS_DEV
    when:
      event: push
      branch: master

  ##################
  # PRD ENVIRONMENT
  ##################
  gae:
    environment:
      - GOPATH=/drone
    image: nytimes/drone-gae
    action: update
    project: nyt-games-prd
    version: "$$COMMIT"
    token: >
      $$GOOGLE_CREDENTIALS_PRD
    when:
      event: tag

  gae:
    image: nytimes/drone-gae
    action: set_default_version
    project: nyt-games-prd
    version: "$$COMMIT"
    token: >
      $$GOOGLE_CREDENTIALS_PRD
    when:
      event: tag

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: drone
    channel: games-releases
